name: Export CV as PDF

on:
    push:
      branches:
        - main

jobs:
    convert:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout Repository
          uses: actions/checkout@master

        - name: Install wkhtmltopdf
          run: | 
            sudo apt-get update 
            sudo apt-get install -y wkhtmltopdf
        
        - name: Run convert script
          run: |
            chmod +x ./scripts/convert.sh
            ./scripts/convert.sh
        
        - name: Upload PDF
          uses: actions/upload-artifact@v3
          with:
            name: CV - Joshua Hamilton-Brown.pdf
            path: ./public/cv.pdf


        